"""Initial baseline

Revision ID: 6d60de085836
Revises: 
Create Date: 2026-07-10 17:43:01.145063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d60de085836'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_entries')
    op.create_index(op.f('ix_alerts_game_id'), 'alerts', ['game_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_index(op.f('ix_game_platforms_game_id'), 'game_platforms', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_prices_game_id'), 'game_prices', ['game_id'], unique=False)
    op.alter_column('games', 'target_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_games_user_id'), 'games', ['user_id'], unique=False)
    op.create_unique_constraint('uq_game_user', 'games', ['igdb_id', 'user_id'])
    op.create_foreign_key(None, 'games', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint('uq_game_user', 'games', type_='unique')
    op.drop_index(op.f('ix_games_user_id'), table_name='games')
    op.alter_column('games', 'target_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_game_prices_game_id'), table_name='game_prices')
    op.drop_index(op.f('ix_game_platforms_game_id'), table_name='game_platforms')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_game_id'), table_name='alerts')
    op.create_table('library_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('owned_platform', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('hours_played', sa.FLOAT(), nullable=True),
    sa.Column('enjoyment', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('target_price', sa.FLOAT(), nullable=True),
    sa.Column('watch_store', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
