"""initial schema

Revision ID: f1128d62ca32
Revises: b80e72bb9ebc
Create Date: 2026-07-11 16:57:35.904466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1128d62ca32'
down_revision: Union[str, None] = 'b80e72bb9ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('target_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_games_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_game_user', ['igdb_id', 'user_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('has_splitscreen')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_splitscreen', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_game_user', type_='unique')
        batch_op.drop_index(batch_op.f('ix_games_user_id'))
        batch_op.alter_column('target_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
